In [1]:
#Numpy Tutorial 1 creating Arrays and Dimensional Arrays

In [2]:
#Importing Relevant Modules
import numpy as np

In [3]:
# Creating a simple array
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [5]:
# Let's explore the different size dimensions

#Zero Dimensional Array
zero_dim = np.array(382759138)
print(zero_dim)

#One Dimensional Array

one_dim = np.array([1, 2, 3])
print(one_dim)

382759138
[1 2 3]


In [6]:
#Two Dimensional Array
two_dim = np.array([[1, 2, 3], [4, 5, 6]])
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [7]:
#Three dimensional array
three_dim = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(three_dim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
#Finding the dimension of a given array
print(two_dim.ndim)

2


In [9]:
# Given an array any dimension you want!
new_array = np.array(17, ndmin=5)
print(new_array)

[[[[[17]]]]]


In [10]:
new_array = np.array([1, 2], ndmin=5)
print(new_array)

[[[[[1 2]]]]]
