In [ ]:
!pip install numpy

In [ ]:
!python -m pip install numpy


In [ ]:
!pip install numpy

In [ ]:
import sys


In [ ]:
print(sys.executable)


In [ ]:
!echo $PATH


In [ ]:
import sys
!{sys.executable} -m pip install numpy


In [ ]:
pip install numpy

In [1]:
import numpy as np


In [2]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [3]:
data

array([[[0.95034957, 0.20439886, 0.21080626, 0.98083889],
        [0.07784873, 0.89151076, 0.91135356, 0.79180824],
        [0.48185005, 0.40695618, 0.03084686, 0.54835304]],

       [[0.2806066 , 0.07060465, 0.46325886, 0.06027427],
        [0.13071436, 0.06723972, 0.90828992, 0.70210562],
        [0.16798882, 0.19225242, 0.85275474, 0.232744  ]]])

In [4]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [5]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [6]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [8]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [9]:
 type(arr)

numpy.ndarray

In [10]:
#Attribute
shape = data.shape
size = data.size
types = data.dtype

In [11]:
shape

(2, 3, 4)

In [12]:
size

24

In [13]:
type

type

In [14]:
types

dtype('float64')

In [21]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [16]:
arr

array([[0.95034957, 0.20439886, 0.21080626, 0.98083889],
       [0.07784873, 0.89151076, 0.91135356, 0.79180824],
       [0.48185005, 0.40695618, 0.03084686, 0.54835304]])

In [17]:
slicer

array([[[0.95034957, 0.20439886, 0.21080626, 0.98083889],
        [0.07784873, 0.89151076, 0.91135356, 0.79180824],
        [0.48185005, 0.40695618, 0.03084686, 0.54835304]],

       [[0.2806066 , 0.07060465, 0.46325886, 0.06027427],
        [0.13071436, 0.06723972, 0.90828992, 0.70210562],
        [0.16798882, 0.19225242, 0.85275474, 0.232744  ]]])

In [19]:
slicer

array([0.48185005, 0.40695618, 0.03084686, 0.54835304])

In [20]:
reverse

array([[0.2806066 , 0.07060465, 0.46325886, 0.06027427],
       [0.13071436, 0.06723972, 0.90828992, 0.70210562],
       [0.16798882, 0.19225242, 0.85275474, 0.232744  ]])

In [22]:
slicer

array([[0.95034957, 0.20439886, 0.21080626, 0.98083889],
       [0.07784873, 0.89151076, 0.91135356, 0.79180824]])

In [23]:
singleval

0.9503495737980849

In [24]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [25]:
list2

array([0.01797494, 0.87541415, 0.57692132, 0.43973851, 0.54994048,
       0.21187596, 0.21081912, 0.46803171, 0.44560726, 0.49189563])

In [26]:
#Basic Math

add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [27]:
add

array([0.64443045, 1.01189541, 0.83507825, 1.26191919, 1.31921618,
       0.6314709 , 1.02604231, 1.41726607, 1.24109518, 0.86992126])

In [28]:
sub

array([ 0.60848056, -0.73893289, -0.31876439,  0.38244217,  0.21933523,
        0.20771899,  0.60440407,  0.48120265,  0.34988066, -0.11387001])

In [29]:
div

array([34.85160052,  0.15590479,  0.44747338,  1.86970361,  1.39883448,
        1.98038018,  3.86693192,  2.02814112,  1.78517719,  0.76850779])

In [30]:
mult

array([0.0112605 , 0.11947763, 0.14893624, 0.36154451, 0.42305584,
       0.08890208, 0.17186464, 0.44427178, 0.35447519, 0.18594916])

In [31]:
dot

2.309737562769244

In [43]:
#Stat functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list2)

In [33]:
sqrt

5.0

In [34]:
ab

2

In [35]:
power

128

In [36]:
log

3.2188758248682006

In [37]:
exp

[2, 3]

In [38]:
mins

0.1364812590045763

In [39]:
max

<function max>

In [40]:
maxs

0.8754141528245627

In [42]:
exp

[2, 3]

In [44]:
exp

array([ 7.3890561 , 20.08553692])

In [45]:
data

array([[[0.95034957, 0.20439886, 0.21080626, 0.98083889],
        [0.07784873, 0.89151076, 0.91135356, 0.79180824],
        [0.48185005, 0.40695618, 0.03084686, 0.54835304]],

       [[0.2806066 , 0.07060465, 0.46325886, 0.06027427],
        [0.13071436, 0.06723972, 0.90828992, 0.70210562],
        [0.16798882, 0.19225242, 0.85275474, 0.232744  ]]])

In [46]:
data[0][0][0]

0.9503495737980849

In [47]:
data[0][0][0] = 700

In [48]:
data

array([[[7.00000000e+02, 2.04398863e-01, 2.10806264e-01, 9.80838891e-01],
        [7.78487277e-02, 8.91510763e-01, 9.11353559e-01, 7.91808238e-01],
        [4.81850048e-01, 4.06956176e-01, 3.08468620e-02, 5.48353040e-01]],

       [[2.80606598e-01, 7.06046477e-02, 4.63258862e-01, 6.02742690e-02],
        [1.30714356e-01, 6.72397176e-02, 9.08289918e-01, 7.02105615e-01],
        [1.67988822e-01, 1.92252423e-01, 8.52754736e-01, 2.32744000e-01]]])

In [49]:
print(data.shape)

(2, 3, 4)


In [50]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [52]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [53]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [54]:
data

array([[[7.00000000e+02, 2.04398863e-01, 2.10806264e-01, 9.80838891e-01,
         7.78487277e-02, 8.91510763e-01],
        [9.11353559e-01, 7.91808238e-01, 4.81850048e-01, 4.06956176e-01,
         3.08468620e-02, 5.48353040e-01]],

       [[2.80606598e-01, 7.06046477e-02, 4.63258862e-01, 6.02742690e-02,
         1.30714356e-01, 6.72397176e-02],
        [9.08289918e-01, 7.02105615e-01, 1.67988822e-01, 1.92252423e-01,
         8.52754736e-01, 2.32744000e-01]]])

In [55]:
 np.delete(data, 0, axis=1)

array([[[0.91135356, 0.79180824, 0.48185005, 0.40695618, 0.03084686,
         0.54835304]],

       [[0.90828992, 0.70210562, 0.16798882, 0.19225242, 0.85275474,
         0.232744  ]]])

In [56]:
np.save("new array", data)

In [57]:
test = np.load("new array.npy")

In [58]:
test

array([[[7.00000000e+02, 2.04398863e-01, 2.10806264e-01, 9.80838891e-01,
         7.78487277e-02, 8.91510763e-01],
        [9.11353559e-01, 7.91808238e-01, 4.81850048e-01, 4.06956176e-01,
         3.08468620e-02, 5.48353040e-01]],

       [[2.80606598e-01, 7.06046477e-02, 4.63258862e-01, 6.02742690e-02,
         1.30714356e-01, 6.72397176e-02],
        [9.08289918e-01, 7.02105615e-01, 1.67988822e-01, 1.92252423e-01,
         8.52754736e-01, 2.32744000e-01]]])