In [1]:
import numpy as np

In [3]:
my_array = np.arange(8)
print(my_array)
print(type(my_array))

[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [6]:
my_array = np.arange(1, 8)
print(my_array)
print(type(my_array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [7]:
my_array = np.arange(1, 8, 0.5)
print(my_array)
print(type(my_array))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]
<class 'numpy.ndarray'>


In [10]:
#arrays from lists (added dtype=np.int8 second)
from_list = np.array([1, 2, 3], dtype=np.int8)
print(from_list)


[1 2 3]


In [9]:
print(type(from_list[0]))

<class 'numpy.int64'>


In [11]:
print(type(from_list[0]))

<class 'numpy.int8'>


In [12]:
#2D arrays
from_list = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int8)
print(from_list)


[[1 2 3]
 [4 5 6]]


In [15]:
array_2d = np.array((np.arange(0,8,2), np.arange(1,8,2)))
print(array_2d)                   

[[0 2 4 6]
 [1 3 5 7]]


In [16]:
print("2D shape:", array_2d.shape)

2D shape: (2, 4)


In [17]:
print("1D shape:", my_array.shape)

1D shape: (14,)


In [18]:
array_2d.reshape((4, 2))
print(array_2d)

[[0 2 4 6]
 [1 3 5 7]]


In [19]:
print("2D shape:", array_2d.shape)

2D shape: (2, 4)


In [21]:
array_2d = array_2d.reshape((4, 2))
print("2D shape:", array_2d.shape)

2D shape: (4, 2)


In [23]:
array_2d = array_2d.reshape((2, 1, 4))
print("2D shape:", array_2d.shape)
print(array_2d)

2D shape: (2, 1, 4)
[[[0 2 4 6]]

 [[1 3 5 7]]]


In [24]:
#empty arrays
empty_array = np.zeros((2,2))
print(empty_array)

[[0. 0.]
 [0. 0.]]


In [25]:
#empty ones
empty_array = np.ones((2,2))
print(empty_array)

[[1. 1.]
 [1. 1.]]


In [26]:
#empty empty arrays
empty_array = np.empty((2,2))
print(empty_array)

[[1. 1.]
 [1. 1.]]


In [27]:
empty_array = np.empty((2,2,2))
print(empty_array)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [28]:
eye_array = np.eye(3)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
eye_array = np.eye(3, k=-1)
print(eye_array)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [30]:
eye_array = np.eye(3, k=1)
print(eye_array)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [31]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
print(eye_array)

[[2. 1. 2.]
 [2. 2. 1.]
 [2. 2. 2.]]


In [32]:
eye_array = np.eye(3, k=1)
eye_array[eye_array < 2 ] = 9
print(eye_array)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [33]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2 ] = 9
print(eye_array)

[[2. 9. 2.]
 [2. 2. 9.]
 [2. 2. 2.]]


In [34]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2 ] = 9
eye_array[0] = 3
print(eye_array)

[[3. 3. 3.]
 [2. 2. 9.]
 [2. 2. 2.]]


In [35]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2 ] = 9
eye_array[:2] = 3
print(eye_array)

[[3. 3. 3.]
 [3. 3. 3.]
 [2. 2. 2.]]


In [36]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2 ] = 9
eye_array[1:] = 3
print(eye_array)

[[2. 9. 2.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [37]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2 ] = 9
eye_array[:, 0] = 4
print(eye_array)

[[4. 9. 2.]
 [4. 2. 9.]
 [4. 2. 2.]]


In [38]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2 ] = 9
eye_array[: -1] = 4
print(eye_array)

[[4. 4. 4.]
 [4. 4. 4.]
 [2. 2. 2.]]


In [41]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2 ] = 9
eye_array[1:] = 3
eye_array[:, -1] = 4
print(eye_array)

[[2. 9. 4.]
 [3. 3. 4.]
 [3. 3. 4.]]


In [42]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
eye_array[eye_array < 2 ] = 9
eye_array[1:] = 3
eye_array[1:, :2] = 4
print(eye_array)

[[2. 9. 2.]
 [4. 4. 3.]
 [4. 4. 3.]]


In [43]:
print(eye_array, "\n")

sorted_array = np.sort(eye_array)
print(sorted_array)

[[2. 9. 2.]
 [4. 4. 3.]
 [4. 4. 3.]] 

[[2. 2. 9.]
 [3. 4. 4.]
 [3. 4. 4.]]


In [44]:
print(eye_array, "\n")

sorted_array = np.sort(eye_array, axis=0)
print(sorted_array)

[[2. 9. 2.]
 [4. 4. 3.]
 [4. 4. 3.]] 

[[2. 4. 2.]
 [4. 4. 3.]
 [4. 9. 3.]]


In [45]:
print(eye_array, "\n")

sorted_array = np.sort(eye_array, axis=1)
print(sorted_array)

[[2. 9. 2.]
 [4. 4. 3.]
 [4. 4. 3.]] 

[[2. 2. 9.]
 [3. 4. 4.]
 [3. 4. 4.]]


In [46]:
print(eye_array, "\n")

sorted_array = np.sort(eye_array, axis=0, kind="mergesort")
print(sorted_array)

[[2. 9. 2.]
 [4. 4. 3.]
 [4. 4. 3.]] 

[[2. 4. 2.]
 [4. 4. 3.]
 [4. 9. 3.]]


In [47]:
print(eye_array, "\n")

sorted_array = np.sort(eye_array, axis=0, kind="heapsort")
print(sorted_array)

[[2. 9. 2.]
 [4. 4. 3.]
 [4. 4. 3.]] 

[[2. 4. 2.]
 [4. 4. 3.]
 [4. 9. 3.]]


In [48]:
#copy arrays
my_view = sorted_array.view()
my_copy = sorted_array.copy()

my_view[:] = 4
print(my_view, "\n")
print(sorted_array)

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
